from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel, Field


class SchemaMappingReport(BaseModel):
    """Report generated by SchemaInspector detailing field resolution."""
    mapped_fields: dict[str, str] = Field(
        default_factory=dict,
        description="Dictionary mapping actual source field names to canonical internal fields."
    )
    unmapped_fields: list[str] = Field(
        default_factory=list,
        description="List of raw source fields that did not map to any canonical field."
    )
    missing_canonical_fields: list[str] = Field(
        default_factory=list,
        description="List of canonical fields that were not found in the source."
    )
    coverage_percentage: float = Field(
        default=0.0,
        description="Percentage of canonical fields successfully mapped."
    )

class SchemaInspector:
    """
    Inspects source fields and maps them to canonical internal fields
    based on a configurable YAML mapping file.
    """
    def __init__(self, mapping_file_path: Path | str | None = None) -> None:
        if mapping_file_path is None:
            # Default to the configs directory in the project root
            base_dir = Path(__file__).resolve().parent.parent.parent.parent
            mapping_file_path = base_dir / "configs" / "field_mapping.yaml"

        self.mapping_file_path = Path(mapping_file_path)
        self._config: dict[str, Any] = self._load_config()
        self.canonical_definitions = self._config.get("canonical_fields", {})

    def _load_config(self) -> dict[str, Any]:
        if not self.mapping_file_path.exists():
            raise FileNotFoundError(f"Mapping configuration not found at {self.mapping_file_path}")
        with open(self.mapping_file_path, encoding="utf-8") as f:
            return yaml.safe_load(f) or {}

    def inspect_and_map(self, discovered_fields: list[str]) -> SchemaMappingReport:
        """
        Maps a list of discovered fields to the canonical schema.

        Args:
            discovered_fields: A flat list of field names found in the source.

        Returns:
            SchemaMappingReport containing the resolution results.
        """
        discovered_set = set(discovered_fields)
        mapped_source_fields = set()

        result_mapped: dict[str, str] = {}
        missing_canonical: list[str] = []

        # 1. Resolve canonical fields
        for canonical_name, config in self.canonical_definitions.items():
            candidates = config.get("candidates", [])
            resolved_field = None

            # Check candidates in order of preference
            for candidate in candidates:
                if candidate in discovered_set:
                    resolved_field = candidate
                    break

            if resolved_field:
                result_mapped[resolved_field] = canonical_name
                mapped_source_fields.add(resolved_field)
            else:
                missing_canonical.append(canonical_name)

        # 2. Identify unmapped (unknown) fields to be retained in raw/extra
        unmapped = [f for f in discovered_fields if f not in mapped_source_fields]

        # 3. Calculate coverage percentage
        total_canonical = len(self.canonical_definitions)
        found_canonical = total_canonical - len(missing_canonical)
        coverage = (found_canonical / total_canonical * 100.0) if total_canonical > 0 else 100.0

        return SchemaMappingReport(
            mapped_fields=result_mapped,
            unmapped_fields=unmapped,
            missing_canonical_fields=missing_canonical,
            coverage_percentage=coverage
        )
